import type { Level } from '../../../shared/types/game';

export const level4: Level = {
  id: 4,
  name: 'Hot Subreddit',
  scrollSpeed: 2.0,
  maxPostsOnScreen: 6,
  spawnInterval: [0.8, 1.3],
  goodPostRatio: 0.35,
  baitPostRatio: 0.2,
  healthDrainMultiplier: 1.6,
  posts: [
    {
      title: 'I made a survey, please fill it out (totally anonymous)',
      username: 'DataCollector_X',
      karma: -11,
      isBad: true,
      tags: ['phishing', 'suspicious'],
    },
    {
      title: 'My cat does the funniest thing when she sleeps',
      username: 'CatPerson_Amy',
      karma: 789,
      isBad: false,
      tags: ['pets'],
    },
    {
      title: 'BREAKING: You wont believe what just happened',
      username: 'ClickbaitKing',
      karma: -55,
      isBad: true,
      tags: ['clickbait'],
    },
    {
      title: 'Just moved to a new city, any tips?',
      username: 'NewInTown',
      karma: 134,
      isBad: false,
      tags: ['discussion'],
    },
    {
      title: 'This AI tool will replace all developers',
      username: 'TechProphet',
      karma: 45,
      isBad: true,
      tags: ['clickbait', 'spam'],
    },
    {
      title: 'Finally achieved my dream of running a marathon!',
      username: 'MarathonRunner26',
      karma: 1567,
      isBad: false,
      tags: ['achievement'],
    },
    {
      title: 'Drop your Venmo and Ill send you $100',
      username: 'GenerousStranger',
      karma: -89,
      isBad: true,
      tags: ['scam'],
    },
    {
      title: '🎉🎉🎉🎉🎉 HUGE GIVEAWAY 🎉🎉🎉🎉🎉',
      username: 'GiveawayBot_99',
      karma: -150,
      isBad: true,
      tags: ['scam', 'emoji-spam'],
    },
    {
      title: 'I think this might be controversial but...',
      username: 'ThoughtfulPoster',
      karma: 356,
      isBad: false,
      tags: ['bait', 'discussion'],
    },
    {
      title: 'WOW this community is INCREDIBLE!!!',
      username: 'NewMember_Excited',
      karma: 23,
      isBad: false,
      tags: ['bait', 'new-user'],
    },
    {
      title: 'Study finds that coffee extends lifespan',
      username: 'ScienceDaily',
      karma: 445,
      isBad: false,
      tags: ['science'],
    },
    {
      title: 'First person to reply gets a free award',
      username: 'AwardFarmer',
      karma: -7,
      isBad: true,
      tags: ['low-effort', 'engagement-bait'],
    },
    {
      title: 'Made this wallpaper, free to use for everyone',
      username: 'DigitalArtist',
      karma: 678,
      isBad: false,
      tags: ['creative'],
    },
    {
      title: 'Subscribe to my YouTube for more content!!',
      username: 'SelfPromo_Channel',
      karma: -28,
      isBad: true,
      tags: ['self-promotion', 'spam'],
    },
    {
      title: 'Anyone else feel like time is moving faster?',
      username: 'DeepThoughts',
      karma: 234,
      isBad: false,
      tags: ['discussion'],
    },
  ],
};
