import type { Level } from '../../../shared/types/game';

export const level2: Level = {
  id: 2,
  name: 'Novice Mod',
  scrollSpeed: 1.2,
  maxPostsOnScreen: 4,
  spawnInterval: [1.2, 1.8],
  goodPostRatio: 0.45,
  baitPostRatio: 0.1,
  healthDrainMultiplier: 1.2,
  posts: [
    {
      title: 'FREE V-BUCKS GENERATOR NO SURVEY',
      username: 'FreeStuffBot',
      karma: -33,
      isBad: true,
      tags: ['scam'],
    },
    {
      title: 'This product changed my life!! Not sponsored I swear',
      username: 'TotallyReal_User',
      karma: 2,
      isBad: true,
      tags: ['spam', 'suspicious'],
    },
    {
      title: 'SEND ME YOUR PASSWORD FOR FREE PREMIUM',
      username: 'Reddit_Admin_Official',
      karma: -200,
      isBad: true,
      tags: ['scam', 'phishing'],
    },
    {
      title: 'upvote if you agree, downvote if you disagree',
      username: 'VoteManipulator',
      karma: -8,
      isBad: true,
      tags: ['low-effort', 'vote-manipulation'],
    },
    {
      title: 'I finally beat my personal record at the gym!',
      username: 'FitnessJourney',
      karma: 312,
      isBad: false,
      tags: ['wholesome'],
    },
    {
      title: 'Hot take: pineapple on pizza is actually great',
      username: 'PizzaDebater',
      karma: 156,
      isBad: false,
      tags: ['discussion'],
    },
    {
      title: 'My dog learned a new trick today',
      username: 'ProudDogParent',
      karma: 89,
      isBad: false,
      tags: ['wholesome'],
    },
    {
      title: 'OMG I JUST GOT PROMOTED!! SO EXCITED!!!',
      username: 'CareerWins',
      karma: 423,
      isBad: false,
      tags: ['bait', 'excited'],
    },
    {
      title: 'Check out this AMAZING sunset I captured',
      username: 'NaturePhotog',
      karma: 678,
      isBad: false,
      tags: ['bait', 'photography'],
    },
    {
      title: '💎🙌 TO THE MOON 🚀🚀🚀',
      username: 'CryptoHype_2024',
      karma: -45,
      isBad: true,
      tags: ['spam', 'emoji-spam'],
    },
    {
      title: 'What is your unpopular opinion?',
      username: 'CuriousMind99',
      karma: 234,
      isBad: false,
      tags: ['discussion'],
    },
    {
      title: 'repost repost repost upvote plz',
      username: 'RepostKing',
      karma: -12,
      isBad: true,
      tags: ['low-effort', 'repost'],
    },
  ],
};
