import type { Level } from '../../../shared/types/game';

export const level1: Level = {
  id: 1,
  name: 'Training',
  scrollSpeed: 0.8,
  maxPostsOnScreen: 3,
  spawnInterval: [1.5, 2.0],
  goodPostRatio: 0.5,
  baitPostRatio: 0,
  healthDrainMultiplier: 1.0,
  posts: [
    {
      title: '🚀 FREE CRYPTO NOW!!! 🔥🔥🔥',
      username: 'DefinitelyNotAScam',
      karma: -42,
      isBad: true,
      tags: ['scam', 'emoji-spam'],
    },
    {
      title: 'CLICK HERE FOR FREE REDDIT GOLD!!!',
      username: 'Bot_GoldGiver99',
      karma: -15,
      isBad: true,
      tags: ['scam', 'all-caps'],
    },
    {
      title: '💰💰💰 INSTANT MONEY HACK 💰💰💰',
      username: 'SpammerX2000',
      karma: -88,
      isBad: true,
      tags: ['scam', 'emoji-spam'],
    },
    {
      title: 'UPVOTE IF YOU BREATHE AIR!!!',
      username: 'KarmaBot_001',
      karma: -5,
      isBad: true,
      tags: ['low-effort', 'all-caps'],
    },
    {
      title: 'Just adopted this little guy from the shelter!',
      username: 'HappyPetOwner',
      karma: 245,
      isBad: false,
      tags: ['wholesome'],
    },
    {
      title: 'What are your favorite comfort foods?',
      username: 'FoodLover42',
      karma: 89,
      isBad: false,
      tags: ['discussion'],
    },
    {
      title: 'TIL that octopuses have three hearts',
      username: 'ScienceFacts',
      karma: 567,
      isBad: false,
      tags: ['educational'],
    },
    {
      title: 'My garden is finally blooming this spring',
      username: 'GreenThumb_Lisa',
      karma: 134,
      isBad: false,
      tags: ['wholesome'],
    },
    {
      title: 'Can anyone recommend a good book?',
      username: 'BookwormSteve',
      karma: 45,
      isBad: false,
      tags: ['discussion'],
    },
    {
      title: '🔥🔥🔥 BUY NOW BEFORE ITS GONE 🔥🔥🔥',
      username: 'NotAScammer_Trust',
      karma: -120,
      isBad: true,
      tags: ['scam', 'emoji-spam'],
    },
  ],
};
