import type { Level } from '../../../shared/types/game';

export const level3: Level = {
  id: 3,
  name: 'Active Sub',
  scrollSpeed: 1.6,
  maxPostsOnScreen: 5,
  spawnInterval: [1.0, 1.5],
  goodPostRatio: 0.4,
  baitPostRatio: 0.15,
  healthDrainMultiplier: 1.4,
  posts: [
    {
      title: 'Earn $5000/day working from home! DM me',
      username: 'WorkFromHome_Pro',
      karma: -67,
      isBad: true,
      tags: ['scam'],
    },
    {
      title: 'This hidden trick doctors dont want you to know',
      username: 'HealthHacks101',
      karma: 3,
      isBad: true,
      tags: ['clickbait'],
    },
    {
      title: 'Follow my Instagram for daily motivation',
      username: 'InfluencerLife',
      karma: -22,
      isBad: true,
      tags: ['self-promotion', 'spam'],
    },
    {
      title: 'Why is nobody talking about this??',
      username: 'ConspiracyGuy',
      karma: 15,
      isBad: true,
      tags: ['clickbait', 'suspicious'],
    },
    {
      title: 'Just finished building my first PC!',
      username: 'PCBuilder_Newbie',
      karma: 445,
      isBad: false,
      tags: ['tech'],
    },
    {
      title: 'Recipe: The best chocolate chip cookies ever',
      username: 'HomeBaker',
      karma: 892,
      isBad: false,
      tags: ['cooking'],
    },
    {
      title: 'I hiked to the top of Mt. Rainier yesterday',
      username: 'TrailRunner_PNW',
      karma: 567,
      isBad: false,
      tags: ['outdoors'],
    },
    {
      title: 'INSANE deal alert!! Only 3 left!!',
      username: 'DealFinder',
      karma: 78,
      isBad: true,
      tags: ['spam', 'clickbait'],
    },
    {
      title: 'THIS IS NOT A DRILL!! HUGE NEWS!!!',
      username: 'ExcitedUser2024',
      karma: 234,
      isBad: false,
      tags: ['bait', 'excited'],
    },
    {
      title: 'Unpopular opinion: tabs are better than spaces',
      username: 'CodeDebater',
      karma: 156,
      isBad: false,
      tags: ['bait', 'tech'],
    },
    {
      title: 'Buy my course for only $99 (normally $999)',
      username: 'GuruMarketer',
      karma: -34,
      isBad: true,
      tags: ['scam', 'self-promotion'],
    },
    {
      title: 'My 5-year-old drew this for me',
      username: 'ProudParent',
      karma: 1023,
      isBad: false,
      tags: ['wholesome'],
    },
    {
      title: 'Has anyone tried the new restaurant downtown?',
      username: 'LocalFoodie',
      karma: 67,
      isBad: false,
      tags: ['discussion'],
    },
    {
      title: 'DONT SCROLL!! You NEED to see this!!!',
      username: 'AttentionGrabber',
      karma: -18,
      isBad: true,
      tags: ['clickbait', 'all-caps'],
    },
  ],
};
