import type { Level } from '../../../shared/types/game';

export const level5: Level = {
  id: 5,
  name: 'Chaos Mod',
  scrollSpeed: 2.6,
  maxPostsOnScreen: 7,
  spawnInterval: [0.6, 1.0],
  goodPostRatio: 0.3,
  baitPostRatio: 0.25,
  healthDrainMultiplier: 2.0,
  posts: [
    {
      title: 'Interesting perspective on climate policy',
      username: 'PolicyWonk',
      karma: 234,
      isBad: false,
      tags: ['discussion'],
    },
    {
      title: 'Interesting perspective (click my profile link)',
      username: 'LinkSpammer_X',
      karma: 1,
      isBad: true,
      tags: ['spam', 'subtle'],
    },
    {
      title: 'Just sharing my experience with this product',
      username: 'Totally_Organic',
      karma: 12,
      isBad: true,
      tags: ['astroturfing', 'subtle'],
    },
    {
      title: 'Just sharing my experience moving abroad',
      username: 'ExpatLife',
      karma: 567,
      isBad: false,
      tags: ['personal'],
    },
    {
      title: 'PSA: Dont click suspicious links in DMs',
      username: 'SecurityHelper',
      karma: 890,
      isBad: false,
      tags: ['helpful'],
    },
    {
      title: 'PSA: Check out this link for free stuff',
      username: 'FreeStuff_PSA',
      karma: -3,
      isBad: true,
      tags: ['scam', 'subtle'],
    },
    {
      title: 'My grandma knitted this sweater for me',
      username: 'CozyGrandkid',
      karma: 2345,
      isBad: false,
      tags: ['wholesome'],
    },
    {
      title: 'Need help with a coding problem',
      username: 'JuniorDev_Help',
      karma: 45,
      isBad: false,
      tags: ['help'],
    },
    {
      title: 'Need help logging into your account? DM me',
      username: 'Support_Reddit',
      karma: -67,
      isBad: true,
      tags: ['phishing', 'impersonation'],
    },
    {
      title: 'This community saved my life, thank you all',
      username: 'GratefulMember',
      karma: 4567,
      isBad: false,
      tags: ['wholesome', 'bait'],
    },
    {
      title: 'Anyone want to join a group chat? Drop username',
      username: 'ChatCollector',
      karma: -14,
      isBad: true,
      tags: ['data-harvesting', 'suspicious'],
    },
    {
      title: 'Found this weird trick to get more karma',
      username: 'KarmaHacker',
      karma: 8,
      isBad: true,
      tags: ['spam', 'clickbait'],
    },
    {
      title: 'Beautiful sunrise from my balcony this morning',
      username: 'MorningViews',
      karma: 1234,
      isBad: false,
      tags: ['photography'],
    },
    {
      title: 'Best coffee shops in Seattle? Visiting next week',
      username: 'TravelPlanner',
      karma: 89,
      isBad: false,
      tags: ['discussion'],
    },
    {
      title: 'I am definitely a real person and not a bot',
      username: 'Human_Person_01',
      karma: -99,
      isBad: true,
      tags: ['bot', 'suspicious'],
    },
    {
      title: 'Why do my posts keep getting removed?',
      username: 'ConfusedUser',
      karma: 23,
      isBad: false,
      tags: ['meta', 'bait'],
    },
    {
      title: 'Verified insider info about upcoming changes',
      username: 'InsiderLeaks',
      karma: -45,
      isBad: true,
      tags: ['misinformation', 'clickbait'],
    },
    {
      title: 'My take on the latest season finale',
      username: 'TVCritic_Fan',
      karma: 345,
      isBad: false,
      tags: ['entertainment'],
    },
  ],
};
